// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    CodeJson: typeof import('./components/Editor/codeJson.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    Hamburger: typeof import('./components/Hamburger/Hamburger.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('./components/icon.vue')['default']
    LangSwitch: typeof import('./components/LangSwitch/index.vue')['default']
    RichEditor: typeof import('./components/Editor/richEditor.vue')['default']
    Search: typeof import('./components/Search/index.vue')['default']
    TuiEditor: typeof import('./components/Editor/tuiEditor.vue')['default']
    WorldMap: typeof import('./components/WorldMap.vue')['default']
  }
}

export { }
