#!/bin/sh
###
 # @Author: GeekQiaQia
 # @Date: 2021-07-21 00:09:24
 # @LastEditTime: 2021-12-29 14:53:01
 # @LastEditors: GeekQiaQia
 # @Description:
 # @FilePath: /vue3.0-template-admin/.husky/pre-commit
###
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
